# Generated by Django 5.1.3 on 2024-11-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Menu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoryitem",
            name="price",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
